<?php

namespace Zenstruck\Metadata;

/**
 * @author Kevin Bond <kevinbond@gmail.com>
 *
 * @internal
 */
final class MapGenerator
{
    private const FILE = __DIR__.'/GeneratedMap.php';
    private const TEMPLATE = <<<EOT
        <?php

        namespace Zenstruck\\Alias\\Composer;

        /**
         * @generated by zenstruck/class-alias
         *
         * @internal
         */
        final class GeneratedAliasMap
        {
            public const CLASS_TO_ALIAS = %s;
            public const ALIAS_TO_CLASS = %s;
            public const METADATA_MAP = %s;
            public const METADATA_KEY_TO_CLASS = %s;
        }

        EOT;

    public static function generateStub(): void
    {
        self::createFile(new Map());
    }

    public static function removeFile(): void
    {
        if (\file_exists(self::FILE)) {
            \unlink(self::FILE);
        }
    }

    private static function createFile(Map $map): void
    {
        \file_put_contents(self::FILE, \sprintf(
            self::TEMPLATE,
            \var_export($map->classToAliasMap, true),
            \var_export($map->aliasToClassMap, true),
            \var_export($map->metadataMap, true),
            \var_export($map->metadataKeyToClassMap, true),
        ));
    }
}
