<?php

namespace Zenstruck\Metadata;

use Composer\ClassMapGenerator\ClassMapGenerator;

/**
 * @author Kevin Bond <kevinbond@gmail.com>
 *
 * @internal
 */
final class MapGenerator
{
    public const FILE = __DIR__.'/GeneratedMap.php';
    private const TEMPLATE = <<<EOT
        <?php

        namespace Zenstruck\\Metadata;

        /**
         * @generated by zenstruck/class-metadata
         *
         * @internal
         */
        final class GeneratedMap
        {
            public const CLASS_TO_ALIAS = %s;
            public const ALIAS_TO_CLASS = %s;
            public const METADATA_MAP = %s;
            public const METADATA_KEY_TO_CLASS = %s;
        }

        EOT;

    /**
     * @param string[]                                        $paths
     * @param array<class-string,string|array<string,scalar>> $mapping
     */
    public static function generate(array $paths, array $mapping): void
    {
        $map = new Map();
        $generator = new ClassMapGenerator();

        foreach ($paths as $path) {
            $generator->scanPaths($path);
        }

        $classMap = $generator->getClassMap();
        $classMap->sort();

        foreach (\array_keys($classMap->getMap()) as $class) {
            $map->addFromClass($class);
        }

        foreach ($mapping as $class => $config) {
            if (!\class_exists($class)) {
                throw new \InvalidArgumentException(\sprintf('Cannot map metadata for "%s" - this class does not exist.', $class));
            }

            $map->addFromConfig($class, $config);
        }

        self::createFile($map);
    }

    public static function removeFile(): void
    {
        if (\file_exists(self::FILE)) {
            \unlink(self::FILE);
        }
    }

    private static function createFile(Map $map): void
    {
        \file_put_contents(self::FILE, \sprintf(
            self::TEMPLATE,
            \var_export($map->classToAliasMap, true),
            \var_export($map->aliasToClassMap, true),
            \var_export($map->metadataMap, true),
            \var_export($map->metadataKeyToClassMap, true),
        ));
    }
}
